# SSH WS + Xray None TLS — พอร์ต 80 (path-based)
server {
    listen 80;
    listen [::]:80;
    server_name _;

    access_log  /dev/null;
    error_log  /dev/null;

    # Xray None TLS
    location /vless {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:10009;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /vmess {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:10010;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    # ที่เหลือ (/, /ssh-ws) = SSH Websocket → SSH 22
    location / {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:8081;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
