#!/bin/bash
clear
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
echo -e "\e[42m                 ต่ออายุผู้ใช้             \E[0m"
echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
read -p "ชื่อผู้ใช้ : " User

if getent passwd $User >/dev/null 2>&1; then
    ok="ok"
else
    echo -e "ล้มเหลว: ผู้ใช้ $User ไม่พบ."
    echo ""
    read -n 1 -s -r -p "กดปุ่มใดๆ เพื่อกลับไปที่เมนู"
    menu
fi

if [ -z $User ]; then
    echo -e "ชื่อผู้ใช้ไม่สามารถเว้นว่างได้"
    echo ""
    read -n 1 -s -r -p "กดปุ่มใดๆ เพื่อกลับไปที่เมนู"
    menu
fi

egrep "^$User" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
    read -p "ขยายวัน : " Days
    if [ -z $Days ]; then
        Days="1"
    fi
    Today=$(date +%s)
    Days_Detailed=$(($Days * 86400))
    Expire_On=$(($Today + $Days_Detailed))
    Expiration=$(date -u --date="1970-01-01 $Expire_On sec GMT" +%Y/%m/%d)
    Expiration_Display=$(date -u --date="1970-01-01 $Expire_On sec GMT" '+%d %b %Y')
    passwd -u $User
    usermod -e $Expiration $User
    egrep "^$User" /etc/passwd >/dev/null
    echo -e "$Pass\n$Pass\n" | passwd $User &>/dev/null
    clear
    echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
    echo -e "\e[42m                 ต่ออายุผู้ใช้             \E[0m"
    echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
    echo -e "   ชื่อผู้ใช้   : $User"
    echo -e "   เพิ่มวัน : $Days วัน"
    echo -e "   หมดอายุใน : $Expiration_Display"
else
    clear
    echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
    echo -e "\e[42m                 ต่ออายุผู้ใช้             \E[0m"
    echo -e "\033[1;93m─────────────────────────────────────────\033[0m"
    echo -e "ไม่พบชื่อผู้ใช้      "
fi
echo ""
read -n 1 -s -r -p "กดปุ่มใดๆ เพื่อกลับไปที่เมนู"
menu