#!/bin/bash
export PATH=/usr/sbin:/usr/bin:/sbin:/bin
case "$1" in
    create)
        /usr/sbin/useradd -m -s /bin/sh "$2" 2>/dev/null
        echo "$2:$3" | /usr/sbin/chpasswd 2>/dev/null
        EXP_TS=$(date -d "+$4 days" +%s)
        /usr/sbin/chage -E $(date -d "+$4 days" +%Y-%m-%d) "$2" 2>/dev/null
        echo "### $2 $EXP_TS" >> /etc/ssh/.ssh.db
        echo "OK"
        ;;
    delete)
        /usr/sbin/userdel -r "$2" 2>/dev/null
        sed -i "/### $2/d" /etc/ssh/.ssh.db 2>/dev/null
        echo "OK"
        ;;
    passwd)
        echo "$2:$3" | /usr/sbin/chpasswd 2>/dev/null
        echo "OK"
        ;;
esac
